[package]
name = "aoc-6-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
die = "0.2.0"
io = "0.0.2"
